return {
	["ak47"] = {
		["Name"] = "AK-47",
		["Damage"] = 36,
		["Price"] = 2700,
		["Fire Rate"] = 600,
		["Magazine Size"] = 30,
		["Ammo in Reserve"] = 90,
		["FullAuto"] = 1,
		["Tracers"] = "Every Third",
		["Bullet Range"] = 8192,
		["KillAward"] = 300,
		["Armor Penetration"] = 0.775,
		["Damage to Armor"] = 4.05,
		["Damage (Chest & Arms)"] = 35,
		["Damage  (Head)"] = 143,
		["Damage (Stomach)"] = 44,
		["Damage (Legs)"] = 26,
		["Damage (Vest: Chest & Arms)"] = 27,
		["Damage (Helmet)"] = 111,
		["Damage (Vest: Stomach)"] = 34,
		["Type"] = "primary",
	},
	["deagle"] = {
		["Name"] = "Desert Eagle",
		["Damage"] = 53,
		["Price"] = 700,
		["Fire Rate"] = 266.6666667,
		["Magazine Size"] = 7,
		["Ammo in Reserve"] = 35,
		["FullAuto"] = 0,
		["Tracers"] = "Every Bullet",
		["Bullet Range"] = 4096,
		["KillAward"] = 300,
		["Armor Penetration"] = 0.932,
		["Damage to Armor"] = 1.802,
		["Damage (Chest & Arms)"] = 52,
		["Damage  (Head)"] = 205,
		["Damage (Stomach)"] = 65,
		["Damage (Legs)"] = 39,
		["Damage (Vest: Chest & Arms)"] = 49,
		["Damage (Helmet)"] = 191,
		["Damage (Vest: Stomach)"] = 61,
		["Type"] = "secondary",
	},
}
